name: Reusable Home Flux Deploy
# This could probably have been done simpler by just outputting the OLD image+tag from a deploy. Then a 'revert' would just be 'fix-forward' commit the old image tag
# Would remove logic from 'revert/deploy in here'

on:
  workflow_call:
    inputs:
      old-image:
        description: The old image to deploy (Minus the tag)
        type: string
      runners:
        description: The name of the runners to execute the job on
        type: string
      deploy-image:
        description: The image to deploy (Including the tag)
        type: string
      flux-file:
        description: The Flux File to edit
        type: string
      revert:
        description: Is this a revert
        type: boolean
        default: false
      revert-sha:
        description: The SHA of the commit to revert
        type: string
    outputs:
      deploy-sha:
        description: "The deployed flux repo sha"
        value: ${{ jobs.deploy.outputs.deploy-sha }}

jobs:
  deploy:
    runs-on: ${{ inputs.runners }}
    outputs:
      deploy-sha: ${{ steps.flux-sha.outputs.FLUX_SHA }}
    steps:
      - name: Checkout Flux Repo
        uses: actions/checkout@v4
        with:
          repository: bl-robinson/home-flux
          path: flux
          fetch-depth: 0
      - name: Unset existing github auth
        # This step is needed as GHA auto sets some config which the setup-git action below does not clear. Need to raise an issue there.
        run: git config --unset-all http.https://github.com/.extraheader
        working-directory: ./flux
      - name: Setup Git
        uses: actions4git/setup-git@v1
        with:
          github-token: ${{ secrets.PUSH_TOKEN }}
          safe-directory: ./flux
      - name: Update Image Ref
        if: ${{ inputs.revert == false }}
        run: sed -i -e 's_${{ inputs.old-image }}:.*_${{ inputs.deploy-image }}_g' ${{ inputs.flux-file }}
        working-directory: ./flux
      - name: Commit change
        if: ${{ inputs.revert == false }}
        working-directory: ./flux
        run: 'git commit ${{ inputs.flux-file }} -m "deploy: Deploying version ${{ inputs.deploy-image }}"'
      - name: Revert Commit
        if: ${{ inputs.revert }}
        working-directory: ./flux
        run: 'git revert ${{ inputs.revert-sha }} --no-edit'
      - name: Get Flux Sha
        id: flux-sha
        working-directory: ./flux
        run: echo "FLUX_SHA=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: Push Commit
        working-directory: ./flux
        run: git push
