name: Reusable Deployment Monitoring

on:
  workflow_call:
    inputs:
      namespace:
        description: The kubernetes namespace the app is deployed in
        type: string
      deployment-name:
        description: The name of the deployment to watch during deploy
        type: string
      kustomization:
        description: The name of the kustomization to watch during deploy
        type: string
      runners:
        description: The name of the runners to execute the job on
        type: string
      flux-sha:
        description: The SHA of the home-flux repo to look for
        type: string

jobs:
  deploy:
    runs-on: ${{ inputs.runners }}
    steps:
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
      - name: Wait for Reconcile
        # I don't really like this line... but it'll do the job... (probably)
        run: timeout 120s sh -c "until kubectl get ks -n ${{ inputs.namespace }} ${{ inputs.kustomization }} -o json | jq '.status.conditions[0].message' | grep 'Applied revision:' | grep '${{ inputs.flux-sha }}'; do echo 'Waiting for Reconciliation...'; sleep 5; done"
      - name: Monitor Deployment
        run: kubectl rollout status -n ${{ inputs.namespace }} deploy/${{ inputs.deployment-name }} --timeout 5m

